apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: nodedb-config-file-app
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: nodedb-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nodedb-app
    spec:
      containers:
      - name: app-container
        # Run this image
        image: shettysagar272/k8s:db-demo-v2_Addinglocalhost

      - name: mongo
        # Run this image
        image: mongo:latest
---

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: nodedb-app-service-config-file
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: nodedb-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer